// tools/make_map.mjs — the distance × radius first-failure map, computed with the page's own
// web/model.js so the map and the live verdict cannot disagree. Usage:
//   node tools/make_map.mjs              → writes web/map_data.js (≈21 min; run under heavy-run)
//   node tools/make_map.mjs --check N    → recompute N cells live, compare to web/map_data.js, print JSON
import fs from "node:fs"; import vm from "node:vm"; import crypto from "node:crypto";
import { execSync } from "node:child_process";
const W = new URL("../web/", import.meta.url);
const GRID = { r_log10: [-0.3011, 2, 80], R_log10: [1, 5, 60] };
const SIGMAS = ["0.7", "1.5", "3.1"], ORGS = ["algal", "vascular"];
const CLASSES = ["HELD", "BURST", "FREEZE", "BOIL", "STARVE", "OPAQUE", "NO_DESIGN"];
export function loadModel() {
  const ctx = { console }; ctx.window = ctx; vm.createContext(ctx);
  for (const f of ["spectral_table.js", "model.js"]) vm.runInContext(fs.readFileSync(new URL(f, W), "utf8"), ctx);
  return ctx.DysonModel;
}
export function mapCell(M, r, R_m, sigma_Pa, org, inputs) {
  try {
    const st = M.autoState(r, R_m, sigma_Pa, M.PRESETS[org] ?? org, inputs ?? M.REGISTERED);
    return st.report.violated[0] ?? "HELD";
  } catch (e) {
    if (e && e.name === "RunnerError") return "NO_DESIGN";
    throw e; // fail loud: any other error is a bug, not a map class
  }
}
export const axis = ([lo, hi, n], i) => Math.pow(10, lo + ((hi - lo) * i) / (n - 1));

const SLICE_KEYS = SIGMAS.flatMap((s) => ORGS.map((o) => `${s}|${o}`));
const NR = GRID.r_log10[2], NRR = GRID.R_log10[2], PER = NR * NRR;
const sigmaPa = (s) => Number(s) * 1e6;
const sha = (f) => crypto.createHash("sha256").update(fs.readFileSync(new URL(f, W))).digest("hex");

function cellAt(M, flat) {
  const k = SLICE_KEYS[Math.floor(flat / PER)], idx = flat % PER;
  const [s, org] = k.split("|"), i = Math.floor(idx / NRR), j = idx % NRR;
  return { key: k, idx, cls: mapCell(M, axis(GRID.r_log10, i), axis(GRID.R_log10, j), sigmaPa(s), org) };
}

function build() {
  const M = loadModel(), t0 = Date.now(), slices = {};
  for (const k of SLICE_KEYS) {
    const [s, org] = k.split("|"); let str = "";
    for (let i = 0; i < NR; i++) for (let j = 0; j < NRR; j++) {
      const c = mapCell(M, axis(GRID.r_log10, i), axis(GRID.R_log10, j), sigmaPa(s), org);
      const ix = CLASSES.indexOf(c);
      if (ix < 0) throw new Error(`unknown class ${c} at ${k} i=${i} j=${j}`);
      str += ix;
    }
    slices[k] = str;
    process.stderr.write(`${k} done ${((Date.now() - t0) / 1000).toFixed(0)} s\n`);
  }
  const provenance = {
    git_sha: execSync("git rev-parse HEAD", { cwd: new URL("..", W) }).toString().trim(),
    model_js_sha256: sha("model.js"), spectral_table_js_sha256: sha("spectral_table.js"),
    written: new Date().toISOString(), runtime_s: Math.round((Date.now() - t0) / 1000),
  };
  const d = { grid: GRID, classes: CLASSES, slices, provenance };
  fs.writeFileSync(new URL("map_data.js", W),
    `// GENERATED by tools/make_map.mjs; do not edit.\nwindow.DysonMap = ${JSON.stringify(d)};\n`);
  process.stderr.write(`wrote web/map_data.js in ${provenance.runtime_s} s\n`);
}

function check(n) {
  const src = fs.readFileSync(new URL("map_data.js", W), "utf8");
  const m = src.match(/window\.DysonMap = (\{.*\});\s*$/s);
  if (!m) throw new Error("web/map_data.js has no window.DysonMap literal");
  const d = JSON.parse(m[1]), M = loadModel(), total = SLICE_KEYS.length * PER;
  // nearest cell to r 1.20 AU / R 10 km, sigma 0.7 algal (the P1 band)
  const near = (g, v) => Math.round(((Math.log10(v) - g[0]) * (g[2] - 1)) / (g[1] - g[0]));
  const target = SLICE_KEYS.indexOf("0.7|algal") * PER + near(GRID.r_log10, 1.2) * NRR + near(GRID.R_log10, 1e4);
  const picks = new Set([target]); const step = Math.floor(total / (n - 1));
  for (let f = 0; picks.size < n && f < total; f += step) picks.add(f);
  for (let f = 1; picks.size < n; f += step) picks.add(f % total);
  const mismatches = [], seen = new Set();
  for (const f of [...picks].sort((a, b) => a - b)) {
    const c = cellAt(M, f); seen.add(c.cls);
    const stored = d.classes[Number(d.slices[c.key][c.idx])];
    if (stored !== c.cls) mismatches.push({ slice: c.key, idx: c.idx, stored, live: c.cls });
  }
  console.log(JSON.stringify({ checked: picks.size, mismatches, classes_seen: [...seen].sort() }));
}

const ci = process.argv.indexOf("--check");
if (ci >= 0) check(Number(process.argv[ci + 1]) || 12);
else if (import.meta.url === `file://${process.argv[1]}`) build();
