#!/usr/bin/env python3
"""Generate web/spectral_table.js from sim/spectral_table.csv (northstar M1b).

The page must work from `file://`, where `fetch` of a sibling CSV is refused, so the
table reaches the browser as a CLASSIC script that carries the CSV's data rows
verbatim (the same decimal strings, so `parseFloat` in JS and `float` in Python read
the same doubles). No number is recomputed here. tests/test_parity_js.py regenerates
this file in memory and asserts it equals the committed one byte for byte.

Run: python3 tools/make_spectral_js.py
"""

from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLE = ROOT / "sim" / "spectral_table.csv"
OUT = ROOT / "web" / "spectral_table.js"


def render() -> str:
    data = "".join(
        ln
        for ln in TABLE.read_text().splitlines(keepends=True)
        if not ln.startswith("#")
    )
    if "`" in data or "\\" in data or "${" in data:
        raise ValueError("spectral table data would break a JS template literal")
    digest = hashlib.sha256(data.encode()).hexdigest()
    return (
        "// Generated by tools/make_spectral_js.py from sim/spectral_table.csv. Do not hand-edit.\n"
        "// A classic script (not a module, not a fetch) so the page works from file://.\n"
        "(function (root) {\n"
        '  "use strict";\n'
        "  const TABLE = {\n"
        '    source: "sim/spectral_table.csv",\n'
        f'    data_sha256: "{digest}",\n'
        f"    csv: `{data}`,\n"
        "  };\n"
        '  if (typeof module !== "undefined" && module.exports) module.exports = TABLE;\n'
        "  else root.DysonSpectralTable = TABLE;\n"
        '})(typeof globalThis !== "undefined" ? globalThis : this);\n'
    )


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
