# Writes sim/spectral_table.csv: the committed spectral basis for Q4 (§8 M1a0).
#
# ASTM G173-03's NATIVE wavelength grid (2,002 rows, 280 to 4000 nm), four columns:
#   lambda_nm  wavelength, nm, ASTM column 1
#   k_per_m    ice absorption coefficient 4*pi*m_im/lambda, /m, from Warren & Brandt
#              2008; m_im is LOG-SPACE interpolated onto the ASTM grid over the
#              250-4200 nm selection window, exactly as
#              tools/check_greenhouse_transparency.py:62-63 does it.
#   E_AM0      extraterrestrial spectral irradiance, W m^-2 nm^-1, ASTM column 2
#   n_ph       relative photon weight, E_AM0 * lambda / (h c)
#
# A k-only table cannot drive tau_sw or f_photon in CI, where both sources are absent
# by construction (.gitignore:9-10); this is why E_AM0 and n_ph are committed with k.
# The quadrature every consumer applies over this grid is `trapezoid`.
#
# Fetch the two sources first (neither is redistributed by this repository; see
# docs/THIRD-PARTY.md):
#   curl -sL https://atmos.uw.edu/ice_optical_constants/IOP_2008_ASCIItable.dat -o iop2008.dat
#   curl -sL https://raw.githubusercontent.com/pvlib/pvlib-python/2d0ed71e1308293b3081979404f8e90f2f2dde1e/pvlib/data/ASTMG173.csv -o ASTMG173.csv
#
# The formatter is PINNED -- "%.10e" and "\n" line ends -- so the file is byte-stable
# across hosts and tests/test_spectral_table.py can regenerate and compare.
import signal
import sys

signal.signal(
    signal.SIGALRM,
    lambda *_: (sys.stderr.write("aborting: walltime guard\n"), sys.exit(2)),
)
signal.alarm(120)

import hashlib
import math
import subprocess
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
ASTM = ROOT / "ASTMG173.csv"
IOP = ROOT / "iop2008.dat"
OUT = ROOT / "sim" / "spectral_table.csv"

# The pvlib-python commit ASTMG173.csv is pinned to (docs/THIRD-PARTY.md, §6).
PVLIB_COMMIT = "2d0ed71e1308293b3081979404f8e90f2f2dde1e"
QUADRATURE = "trapezoid"
SELECT_LO_NM, SELECT_HI_NM = 250.0, 4200.0
H_PLANCK = 6.62607015e-34
C_LIGHT = 2.99792458e8
FMT = "%.10e"


def _provenance(path):
    raw = path.read_bytes()
    return hashlib.md5(raw).hexdigest(), len(raw)


def load_astm(path=ASTM):
    """ASTM G173 native grid: (lambda_nm, E_AM0) from columns 1 and 2."""
    rows = []
    for line in path.read_text().splitlines():
        p = line.strip().split(",")
        if len(p) < 2:
            continue
        try:
            rows.append((float(p[0]), float(p[1])))
        except ValueError:
            pass
    assert len(rows) > 1900, f"PARSER FAILED on {path.name} -- {len(rows)} rows"
    lam = np.array([r[0] for r in rows])
    e_am0 = np.array([r[1] for r in rows])
    return lam, e_am0


def load_ice(path=IOP):
    """Warren & Brandt 2008: (lambda_nm, m_im) from columns 1 (um) and 3."""
    rows = []
    for line in path.read_text().splitlines():
        p = line.split()
        if len(p) != 3:
            continue
        try:
            rows.append((float(p[0]) * 1000.0, float(p[2])))
        except ValueError:
            pass
    assert len(rows) > 400, f"PARSER FAILED on {path.name} -- {len(rows)} rows"
    il = np.array([r[0] for r in rows])
    im = np.array([r[1] for r in rows])
    return il, im


def k_on_grid(lam_nm, il_nm, m_im):
    """k = 4*pi*m_im/lambda, m_im log-space interpolated (check_greenhouse:62-63)."""
    sel = (il_nm >= SELECT_LO_NM) & (il_nm <= SELECT_HI_NM)
    return (
        4.0
        * math.pi
        * np.exp(np.interp(lam_nm, il_nm[sel], np.log(m_im[sel])))
        / (lam_nm * 1e-9)
    )


def producer_commit():
    try:
        return subprocess.run(
            ["git", "-C", str(ROOT), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def build():
    lam, e_am0 = load_astm()
    il, im = load_ice()
    k = k_on_grid(lam, il, im)
    n_ph = e_am0 * (lam * 1e-9) / (H_PLANCK * C_LIGHT)

    assert len(lam) == 2002, f"expected 2,002 ASTM rows, got {len(lam)}"
    assert lam[0] == 280.0 and lam[-1] == 4000.0, f"grid {lam[0]}..{lam[-1]} nm"
    assert np.all(np.diff(lam) > 0), "ASTM grid is not strictly increasing"

    astm_md5, astm_size = _provenance(ASTM)
    iop_md5, iop_size = _provenance(IOP)
    header = [
        "# sim/spectral_table.csv -- the committed spectral basis for Q4 (northstar design §8, M1a0).",
        "# Generated by tools/make_spectral_table.py; do not hand-edit.",
        f"# producer_commit: {producer_commit()}",
        f"# quadrature: {QUADRATURE}",
        f"# formatter: {FMT} , newline \\n",
        f"# grid: ASTM G173-03 native, {len(lam)} rows, {lam[0]:.0f}-{lam[-1]:.0f} nm",
        f"# source: ASTMG173.csv  md5 {astm_md5}  size {astm_size} B"
        f"  pvlib-python commit {PVLIB_COMMIT}",
        f"# source: iop2008.dat  md5 {iop_md5}  size {iop_size} B"
        "  Warren & Brandt 2008, IOP_2008_ASCIItable.dat",
        f"# k_per_m: 4*pi*m_im/lambda, m_im log-space interpolated over"
        f" {SELECT_LO_NM:.0f}-{SELECT_HI_NM:.0f} nm",
        "# E_AM0: ASTM column 2 (extraterrestrial), W m^-2 nm^-1",
        f"# n_ph: E_AM0*lambda/(h c), h {H_PLANCK} J s, c {C_LIGHT} m/s",
        "lambda_nm,k_per_m,E_AM0,n_ph",
    ]
    lines = list(header)
    for i in range(len(lam)):
        lines.append(
            ",".join(
                FMT % v
                for v in (float(lam[i]), float(k[i]), float(e_am0[i]), float(n_ph[i]))
            )
        )
    return "\n".join(lines) + "\n"


def main():
    for p in (ASTM, IOP):
        if not p.exists():
            sys.stderr.write(
                f"missing source {p.name}; see the fetch commands in this file's header\n"
            )
            return 2
    text = build()
    OUT.write_text(text, newline="\n")
    print(f"wrote {OUT} ({len(text)} B, {len(text.splitlines())} lines)")
    print(f"sha256 {hashlib.sha256(text.encode()).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
