// Port of the Python carbon-budget model to the browser. Pure functions, no DOM,
// no dependencies. Every function names the sim/ lines it came from; the numbers
// are pinned against the Python model by web/fixtures.json (generated by
// tools/make_fixtures.py) through tests/test_parity_js.py.
//
// Deliberately NOT ported: Organism.net_carbon_adapted (sim/organism.py:102-123).
// It is Q2b's runner path and nothing on the page displays it; porting code the
// page never calls would add an untested surface.
//
// Units: irradiance µmol photons m-2 s-1; assimilation/respiration µmol CO2
// m-2 s-1 per unit photosynthetic area; temperature K; distance AU.

// ---- sim/physiology.py:13-19 (constants) ----
export const TSI_W_M2 = 1360.8; // Kopp & Lean 2011, doi:10.1029/2010GL045777
export const PAR_FRACTION = 0.3879; // measured AM0 400-700 nm fraction of TSI (S5)
export const PHOTONS_PER_J = 4.57;
export const T_REF_K = 293.0;
export const Q10 = 2.0;

// ---- sim/thermal.py:17 ----
export const SIGMA_W_M2_K4 = 5.670374419e-8;

// ---- sim/physiology.py:22-30 ----
export function irradiance(
  rAu,
  tsi = TSI_W_M2,
  parFraction = PAR_FRACTION,
  photonsPerJ = PHOTONS_PER_J,
) {
  if (!(rAu > 0)) throw new RangeError(`r_au must be > 0, got ${rAu}`);
  return (tsi / (rAu * rAu)) * parFraction * photonsPerJ;
}

// ---- sim/physiology.py:33-43 ----
export function grossAssimilation(i, aMax, k) {
  if (!(aMax > 0)) throw new RangeError(`a_max must be > 0, got ${aMax}`);
  if (!(k > 0)) throw new RangeError(`k must be > 0, got ${k}`);
  if (!(i >= 0)) throw new RangeError(`irradiance must be >= 0, got ${i}`);
  return (aMax * i) / (i + k);
}

// ---- sim/physiology.py:46-54 ----
export function respiration(rD, t, tRef = T_REF_K, q10 = Q10) {
  if (!(rD >= 0)) throw new RangeError(`r_d must be >= 0, got ${rD}`);
  if (!(t > 0)) throw new RangeError(`t must be > 0 K, got ${t}`);
  if (!(q10 > 0)) throw new RangeError(`q10 must be > 0, got ${q10}`);
  return rD * Math.pow(q10, (t - tRef) / 10.0);
}

// ---- sim/thermal.py:20-46 ----
export function equilibriumTemperature(rAu, areaRatio, emissivity = 1.0, albedo = 0.0) {
  if (!(rAu > 0)) throw new RangeError(`r_au must be > 0, got ${rAu}`);
  if (!(areaRatio > 0)) throw new RangeError(`area_ratio must be > 0, got ${areaRatio}`);
  if (!(emissivity > 0 && emissivity <= 1))
    throw new RangeError(`emissivity must be in (0, 1], got ${emissivity}`);
  if (!(albedo >= 0 && albedo < 1))
    throw new RangeError(`albedo must be in [0, 1), got ${albedo}`);
  const s = TSI_W_M2 / (rAu * rAu);
  return Math.pow((s * (1 - albedo)) / (areaRatio * emissivity * SIGMA_W_M2_K4), 0.25);
}

// ---- sim/thermal.py:49-63. Q2's linear ramp: 0 AT t_min, not just below it. ----
export function temperatureResponse(t, tMin, tOpt) {
  if (!(tOpt > tMin))
    throw new RangeError(`t_opt must be > t_min, got t_opt=${tOpt}, t_min=${tMin}`);
  if (t <= tMin) return 0.0;
  if (t >= tOpt) return 1.0;
  return (t - tMin) / (tOpt - tMin);
}

// ---- sim/thermal.py:65-86. June, Evans & Farquhar (2004) form, Q2b. ----
export function temperatureResponseGaussian(t, tOpt, omega) {
  if (!(omega > 0)) throw new RangeError(`omega must be > 0, got ${omega}`);
  if (!(t > 0)) throw new RangeError(`t must be > 0 K, got ${t}`);
  if (!(tOpt > 0)) throw new RangeError(`t_opt must be > 0 K, got ${tOpt}`);
  const z = (t - tOpt) / omega;
  return Math.exp(-(z * z));
}

// ---- sim/thermal.py:89-107 ----
export function adaptedOptimum(rHomeAu, areaRatio, emissivity = 1.0, albedo = 0.0) {
  return equilibriumTemperature(rHomeAu, areaRatio, emissivity, albedo);
}

// ---- sim/organism.py:27-68. The frozen dataclass as a plain frozen object. ----
export function makeOrganism(fields) {
  const org = {
    t_set: T_REF_K,
    area_ratio: 2.0,
    t_min: 265.15,
    t_opt: 298.15,
    emissivity: 1.0,
    albedo: 0.0,
    omega: 20.0,
    ...fields,
  };
  if (!(org.a_max > 0)) throw new RangeError(`a_max must be > 0, got ${org.a_max}`);
  if (!(org.k > 0)) throw new RangeError(`k must be > 0, got ${org.k}`);
  if (!(org.r_d >= 0)) throw new RangeError(`r_d must be >= 0, got ${org.r_d}`);
  if (!(org.leaf_mass_ratio > 0 && org.leaf_mass_ratio <= 1))
    throw new RangeError(`leaf_mass_ratio must be in (0, 1], got ${org.leaf_mass_ratio}`);
  if (!(org.t_set > 0)) throw new RangeError(`t_set must be > 0 K, got ${org.t_set}`);
  if (!(org.area_ratio > 0))
    throw new RangeError(`area_ratio must be > 0, got ${org.area_ratio}`);
  if (!(org.emissivity > 0 && org.emissivity <= 1))
    throw new RangeError(`emissivity must be in (0, 1], got ${org.emissivity}`);
  if (!(org.albedo >= 0 && org.albedo < 1))
    throw new RangeError(`albedo must be in [0, 1), got ${org.albedo}`);
  if (!(org.t_min > 0)) throw new RangeError(`t_min must be > 0 K, got ${org.t_min}`);
  if (!(org.t_opt > org.t_min))
    throw new RangeError(
      `t_opt must be > t_min, got t_opt=${org.t_opt}, t_min=${org.t_min}`,
    );
  if (!(org.omega > 0)) throw new RangeError(`omega must be > 0, got ${org.omega}`);
  return Object.freeze(org);
}

// ---- sim/organism.py:70-72 ----
export function leafRespiration(org) {
  return respiration(org.r_d, org.t_set);
}

// ---- sim/organism.py:74-78 ----
export function organismRespiration(org) {
  return leafRespiration(org) / org.leaf_mass_ratio;
}

// ---- sim/organism.py:80-86 ----
export function netCarbon(org, rAu, k = null) {
  const kk = k === null ? org.k : k;
  return (
    grossAssimilation(irradiance(rAu), org.a_max, kk) - organismRespiration(org)
  );
}

// ---- sim/organism.py:88-100 ----
export function netCarbonAtEquilibrium(org, rAu, k = null) {
  const kk = k === null ? org.k : k;
  const t = equilibriumTemperature(rAu, org.area_ratio, org.emissivity, org.albedo);
  const f = temperatureResponse(t, org.t_min, org.t_opt);
  const gross = grossAssimilation(irradiance(rAu), org.a_max, kk) * f;
  return gross - respiration(org.r_d, t) / org.leaf_mass_ratio;
}

// ---- sim/organism.py:126-135 ----
export function compensationIrradiance(org, k = null) {
  const r = leafRespiration(org);
  const kk = k === null ? org.k : k;
  if (r >= org.a_max)
    throw new RangeError(
      `leaf respiration ${r} >= a_max ${org.a_max}: no compensation point`,
    );
  return (kk * r) / (org.a_max - r);
}

// Log-spaced grid, the JS equivalent of numpy.geomspace (sim/physiology.py:62).
function geomspace(start, stop, n) {
  const out = new Array(n);
  const logStart = Math.log(start);
  const step = (Math.log(stop) - logStart) / (n - 1);
  for (let i = 0; i < n; i += 1) out[i] = Math.exp(logStart + i * step);
  // numpy pins both endpoints exactly; exp(log(x)) does not always round-trip.
  out[0] = start;
  out[n - 1] = stop;
  return out;
}

// ---- sim/physiology.py:57-79 ----
// Same contract as crossover_distance: bracket on the FIRST sign change of a
// log-spaced grid, then solve inside that bracket. Python uses scipy brentq
// with xtol=1e-6; there is no brentq here, so this bisects to a tighter
// interval (1e-12 AU) than the tolerance parity is checked at, which makes the
// declared crossover tolerance a statement about brentq's xtol rather than
// about this solver. Returns null where Python raises "no sign change".
export function crossoverDistance(netFn, rMin = 0.5, rMax = 100.0, nGrid = 400) {
  if (!(rMin > 0 && rMax > rMin))
    throw new RangeError(`need 0 < r_min < r_max, got ${rMin}, ${rMax}`);
  const grid = geomspace(rMin, rMax, nGrid);
  const vals = grid.map((r) => netFn(r));
  let lo = null;
  for (let i = 0; i < nGrid - 1; i += 1) {
    // Math.sign matches numpy.sign, including the strict `< 0` product test:
    // a node landing exactly on the root reads as "no sign change" in both.
    if (Math.sign(vals[i]) * Math.sign(vals[i + 1]) < 0) {
      lo = i;
      break;
    }
  }
  if (lo === null) return null;
  let a = grid[lo];
  let b = grid[lo + 1];
  let fa = vals[lo];
  for (let it = 0; it < 200 && b - a > 1e-12; it += 1) {
    const m = 0.5 * (a + b);
    const fm = netFn(m);
    if (fm === 0) return m;
    if (Math.sign(fa) * Math.sign(fm) < 0) {
      b = m;
    } else {
      a = m;
      fa = fm;
    }
  }
  return 0.5 * (a + b);
}

// ---- sim/organism.py:138-153 ----
export function crossoverDistanceFor(org, k = null, rMin = 0.5, rMax = 100.0, nGrid = 400) {
  return crossoverDistance((r) => netCarbon(org, r, k), rMin, rMax, nGrid);
}

// ---- sim/organism.py:163-173. Presets copied verbatim; do not edit here. ----
export const VASCULAR = makeOrganism({
  cls: "vascular",
  a_max: 10.0,
  k: 100.0,
  r_d: 0.65,
  leaf_mass_ratio: 0.5,
});
export const ALGAL = makeOrganism({
  cls: "algal",
  a_max: 10.0,
  k: 20.0,
  r_d: 0.24,
  leaf_mass_ratio: 0.8,
  area_ratio: 4.0,
  t_min: 254.65,
});
export const PRESETS = { vascular: VASCULAR, algal: ALGAL };
